FROM node:14-alpine3.10

LABEL version="1.0"
LABEL description="Development image for the Library Mern API"
WORKDIR /app

COPY ["package.json","package-lock.json*","npm-shrinkwrap.json*", "./"]

# Install dependencies and clear npm cache
RUN npm install && npm cache clean --force

COPY . .

# use EXPOSE command to have our port mapped by the docker daemon
EXPOSE 5000

# default dev command
CMD [ "npm", "run", "dev" ]